# Basic Python

## 1. Split this string

In [36]:
s = "Hi there Sam!"

In [37]:
string_parts = s.split()
print("Parts of the string:", string_parts)

Parts of the string: ['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [38]:
planet = "Earth"
diameter = 12742

In [39]:
print("The diameter of {planet} is {diameter} kilometers.".format(planet=planet, diameter=diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [40]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [41]:
grabbed_elem = d['k1'][3]['tricky'][3]['target'][3]
print("Grabbed Element: '{}'".format(grabbed_elem))

Grabbed Element: 'hello'


# Numpy

In [42]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [43]:
ten_zeros = np.zeros(10, dtype=np.uint8)
print(ten_zeros)
print(ten_zeros.shape)

[0 0 0 0 0 0 0 0 0 0]
(10,)


In [44]:
ten_fives = np.full(10, 5, dtype=np.uint8)
print(ten_fives)
print(ten_fives.shape)

[5 5 5 5 5 5 5 5 5 5]
(10,)


## 5. Create an array of all the even integers from 20 to 35

In [45]:
even_ints_20_to_35 = np.arange(20, 35, 2)
print(even_ints_20_to_35)
print(even_ints_20_to_35.shape)

[20 22 24 26 28 30 32 34]
(8,)


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [46]:
# Range 0 to 8 -- In Order
matrix_3by3_0to8_ordered = np.arange(0, 9).reshape((3, 3))
print("Ordered:\n", matrix_3by3_0to8_ordered)

# Range 0 to 8 -- Random
matrix_3by3_0to8_random = np.random.randint(0, 9, (3, 3))
print("Random:\n", matrix_3by3_0to8_random)

Ordered:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Random:
 [[5 8 2]
 [6 1 7]
 [4 5 3]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [47]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a_and_b = np.concatenate((a, b), axis=0)
print("Concatenated:", a_and_b)

Concatenated: [1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [48]:
import pandas as pd


In [49]:
col_names = ["Shape", "Edges"]
data = [
    ["Triangle", 3],
    ["Square", 4],
    ["Pentagon", 5]
]

df_3_by_2 = pd.DataFrame(data, columns=col_names) 
print(df_3_by_2)

      Shape  Edges
0  Triangle      3
1    Square      4
2  Pentagon      5


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [50]:
dates_df = pd.Series(
    pd.date_range(start='2023-01-01', end='2023-02-10')
)
print(dates_df)

0    2023-01-01
1    2023-01-02
2    2023-01-03
3    2023-01-04
4    2023-01-05
5    2023-01-06
6    2023-01-07
7    2023-01-08
8    2023-01-09
9    2023-01-10
10   2023-01-11
11   2023-01-12
12   2023-01-13
13   2023-01-14
14   2023-01-15
15   2023-01-16
16   2023-01-17
17   2023-01-18
18   2023-01-19
19   2023-01-20
20   2023-01-21
21   2023-01-22
22   2023-01-23
23   2023-01-24
24   2023-01-25
25   2023-01-26
26   2023-01-27
27   2023-01-28
28   2023-01-29
29   2023-01-30
30   2023-01-31
31   2023-02-01
32   2023-02-02
33   2023-02-03
34   2023-02-04
35   2023-02-05
36   2023-02-06
37   2023-02-07
38   2023-02-08
39   2023-02-09
40   2023-02-10
dtype: datetime64[ns]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [51]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [53]:
lists_df = pd.DataFrame(lists, columns=['Sl.', 'Text', 'Number'])
print(lists_df)

   Sl. Text  Number
0    1  aaa      22
1    2  bbb      25
2    3  ccc      24
